<?php
/**
 * @file
 * Laravel Example.
 */
use \Drupal\laravel_example\Example\User;

/**
 * Implements hook_menu().
 */
function laravel_example_menu() {

  $items['laravel-example'] = array(
    'title' => 'Laravel Example',
    'page callback' => 'laravel_example_page',
    'page arguments' => array() ,
    'access arguments' => array(
      'access content'
    ) ,
  );

  $items['laravel-example/%'] = array(
    'title' => 'Laravel Example',
    'page callback' => 'laravel_example_detail_page',
    'page arguments' => array(1) ,
    'access arguments' => array(
      'access content'
    ) ,
  );

  return $items;
}

function laravel_example_page(){
  if($users = User::all()){
    dpm($users->toArray());
  }

  return "OK";
}

function laravel_example_detail_page($group) {

  return "OK";
}
